source 'https://github.com/CocoaPods/Specs.git'
source 'https://github.com/conanoc/indy-sdk.git'
platform :ios, '12.0'

target 'wallet-app-ios' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for wallet-app-ios
  pod 'Indy', '1.16.1'
end
